/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Evan
 */
public class Agregar extends javax.swing.JPanel {

    private Juego juego;
    
    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
    }

    public void addMouseListenerToLabels(java.awt.event.MouseListener listener) {
        jButton1.addMouseListener(listener);
    }
    
    public Pregunta create() {
        Pregunta preg = new Pregunta();
        preg.setiType(jComboBox1.getSelectedIndex());
        preg.setPregunta(jTextField1.getText());
        preg.setRespuesta(jTextField2.getText());
        return preg;
    }
    
    public void setJuego(Juego juego) {
        this.juego = juego;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setToolTipText("");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 440, 40));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 440, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona...", "Matemáticas", "Inglés" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 220, 40));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Hot Pizza", 0, 14)); // NOI18N
        jLabel1.setText("Pregunta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, 20));

        jLabel2.setFont(new java.awt.Font("Hot Pizza", 0, 14)); // NOI18N
        jLabel2.setText("Respuesta");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Hot Pizza", 0, 14)); // NOI18N
        jLabel3.setText("Tipo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Hot Pizza", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Agregar");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pregunta preg = create();
//        try {
//            ArrayList<String> arr = Database.getContents(juego.getDatabaseFile());
//            for(String str : arr) {
//                System.out.println(str);
//            }
//        } catch (IOException ex) {
//            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
//        }
        try {
            Database.addObject(juego.getDatabaseFile(), preg);
        } catch (IOException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
        juego.cambiaPanelPrincipal("config");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return jButton1;
    }
}
