/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;

/**
 *
 * @author Evan
 */
public class Editar extends javax.swing.JPanel {
    
    private Juego juego;
    
    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
        jList1.setLayout(new BorderLayout());
        jList1.setCellRenderer(new ElementScroll());
        jList1.setVisibleRowCount(10);
    }
    
    public void loadPreguntas() {
        ArrayList<String> contents = null;
        ArrayList<Pregunta> arrPreguntas = new ArrayList<>();
        try {
            contents = Database.getContents(juego.getDatabaseFile());
            for(String content : contents) {
                arrPreguntas.add(new Pregunta(content));
            }
        } catch (IOException ex) { 
            Logger.getLogger(Editar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jList1.setListData(arrPreguntas.toArray());
    }

    public void setJuego(Juego juego) {
        this.juego = juego;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new JList();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 770, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
