/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author axelsuarez
 */
public class GameOver extends javax.swing.JPanel {

    private Juego juego;
    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();
        jLabel2.setText("Regresar a Menu");
        jLabel2.setHorizontalTextPosition(JLabel.CENTER);
        jLabel2.setVerticalTextPosition(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        puntLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Hot Pizza", 0, 48)); // NOI18N
        jLabel1.setText("Game Over");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Hot Pizza", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_aceptar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 300, 120));

        puntLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        add(puntLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Tu puntuación es:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        juego.cambiaPanelPrincipal("menu");
    }//GEN-LAST:event_jLabel2MouseClicked

    public JLabel getPuntLabel() {
        return puntLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel puntLabel;
    // End of variables declaration//GEN-END:variables

    void addMouseListenerToLabels(MouseListener mouseListener) {
        jLabel2.addMouseListener(mouseListener);
    }

    void setJuego(Juego juego) {
        this.juego = juego;
    }
}
