/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;

/**
 *
 * @author axelsuarez
 */
public class Juego extends javax.swing.JFrame {

    // Variables de clase
    private static int panel;
    private CardLayout card;

    public static int getPanel() {
        return panel;
    }

    public static void setPanel(int panel) {
        Juego.panel = panel;
    }
    
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        getContentPane().setSize(1000, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        card = (CardLayout) jPanel1.getLayout();
        menu1.addMouseListenerToLabels(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent me) {
                // Checamos cuál es el label que se clickea para poder definir qué
                // pantalla sigue
                System.out.println(me.getID() + " " + me.getComponent());
                card.show(jPanel1, "invaders");
            }

            @Override
            public void mouseReleased(MouseEvent me) {
            }

            @Override
            public void mouseEntered(MouseEvent me) {
            }

            @Override
            public void mouseExited(MouseEvent me) {
            }

            @Override
            public void mousePressed(MouseEvent me) {
            }
        });
        
    }
    
    public void changePanel() {
        getContentPane().removeAll();
        switch(panel) {
            case 1:
                getContentPane().removeAll();
                PizzaQuizz pizzaQuizz = new PizzaQuizz();
                getContentPane().add(pizzaQuizz, java.awt.BorderLayout.CENTER);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu1 = new pizzagaiden.Menu();
        pizzaInvaders1 = new pizzagaiden.PizzaInvaders();
        pizzaQuizz1 = new pizzagaiden.PizzaQuizz();
        pizzarama1 = new pizzagaiden.Pizzarama();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(menu1, "menu");

        pizzaInvaders1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.add(pizzaInvaders1, "invaders");

        pizzaQuizz1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.add(pizzaQuizz1, "quizz");

        pizzarama1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.add(pizzarama1, "pizzarama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private pizzagaiden.Menu menu1;
    private pizzagaiden.PizzaInvaders pizzaInvaders1;
    private pizzagaiden.PizzaQuizz pizzaQuizz1;
    private pizzagaiden.Pizzarama pizzarama1;
    // End of variables declaration//GEN-END:variables
}
