/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import javax.swing.JLabel;

/**
 *
 * @author axelsuarez
 */
public class Menu extends javax.swing.JPanel {

    private Juego juego;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inciarJuegoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        configLabel = new javax.swing.JLabel();
        scoresLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 99, 97));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inciarJuegoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/PizzaQuizz/Caja_Color.png"))); // NOI18N
        inciarJuegoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inciarJuegoLabelMouseClicked(evt);
            }
        });
        add(inciarJuegoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setText("Menu Principal");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 270, 89));

        configLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/PizzaQuizz/Caja_Color.png"))); // NOI18N
        configLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configLabelMouseClicked(evt);
            }
        });
        add(configLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        scoresLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/PizzaQuizz/Caja_Color.png"))); // NOI18N
        scoresLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoresLabelMouseClicked(evt);
            }
        });
        add(scoresLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 495, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void inciarJuegoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inciarJuegoLabelMouseClicked
        juego.startJuego();
    }//GEN-LAST:event_inciarJuegoLabelMouseClicked

    private void configLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configLabelMouseClicked
        juego.cambiaPanelPrincipal("config");
    }//GEN-LAST:event_configLabelMouseClicked

    private void scoresLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoresLabelMouseClicked
        juego.cambiaPanelPrincipal("scores");
    }//GEN-LAST:event_scoresLabelMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel configLabel;
    private javax.swing.JLabel inciarJuegoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel scoresLabel;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel1() {
        return inciarJuegoLabel;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return configLabel;
    }

    public JLabel getjLabel4() {
        return scoresLabel;
    }

    void setJuego(Juego juego) {
        this.juego = juego;
    }
}
