/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JLabel;

/**
 *
 * @author axelsuarez
 */
public class PanelPausa extends javax.swing.JPanel implements KeyListener {

    private Juego juego; 
    /**
     * Creates new form panelPausa
     */
    public PanelPausa() {
        initComponents();
        labelReanudar.setText("Reanudar Juego");
        labelReanudar.setHorizontalTextPosition(JLabel.CENTER);
        labelReanudar.setVerticalTextPosition(JLabel.CENTER);
        
        labelDetener.setText("Salir del Juego");
        labelDetener.setHorizontalTextPosition(JLabel.CENTER);
        labelDetener.setVerticalTextPosition(JLabel.CENTER);
        addKeyListener(this);
    }
    
    public void setJuego(Juego juego) {
        this.juego = juego;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelReanudar = new javax.swing.JLabel();
        labelDetener = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Hot Pizza", 0, 48)); // NOI18N
        jLabel1.setText("Juego en Pausa");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        labelReanudar.setFont(new java.awt.Font("Hot Pizza", 0, 24)); // NOI18N
        labelReanudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_aceptar.png"))); // NOI18N
        labelReanudar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReanudarMouseClicked(evt);
            }
        });
        add(labelReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        labelDetener.setFont(new java.awt.Font("Hot Pizza", 0, 24)); // NOI18N
        labelDetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_cancelar.png"))); // NOI18N
        labelDetener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDetenerMouseClicked(evt);
            }
        });
        add(labelDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Menu_Pause.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelReanudarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReanudarMouseClicked
        juego.continueGame();
    }//GEN-LAST:event_labelReanudarMouseClicked

    private void labelDetenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDetenerMouseClicked
        juego.stopJuego();
        juego.cambiaPanelPrincipal("menu");
    }//GEN-LAST:event_labelDetenerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDetener;
    private javax.swing.JLabel labelReanudar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if(e.getKeyCode()== KeyEvent.VK_P) {
            juego.continueGame();
        }
    }
}
