/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import javax.swing.JLabel;

/**
 *
 * @author axelsuarez
 */
public class panelPausa extends javax.swing.JPanel {

    /**
     * Creates new form panelPausa
     */
    public panelPausa() {
        initComponents();
        labelReanudar.setText("Reanudar Juego");
        labelReanudar.setHorizontalTextPosition(JLabel.CENTER);
        labelReanudar.setVerticalTextPosition(JLabel.CENTER);
        
        labelDetener.setText("Salir del Juego");
        labelDetener.setHorizontalTextPosition(JLabel.CENTER);
        labelDetener.setVerticalTextPosition(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelReanudar = new javax.swing.JLabel();
        labelDetener = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 99, 97));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 60)); // NOI18N
        jLabel1.setText("Juego en Pausa");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 98, -1, -1));

        labelReanudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_aceptar.png"))); // NOI18N
        add(labelReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 520, -1, -1));

        labelDetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_cancelar.png"))); // NOI18N
        add(labelDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDetener;
    private javax.swing.JLabel labelReanudar;
    // End of variables declaration//GEN-END:variables
}
