/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import javax.swing.JLabel;

/**
 *
 * @author axelsuarez
 */
public class panelPausa extends javax.swing.JPanel {

    /**
     * Creates new form panelPausa
     */
    public panelPausa() {
        initComponents();
        labelReanudar.setText("Reanudar Juego");
        labelReanudar.setHorizontalTextPosition(JLabel.CENTER);
        labelReanudar.setVerticalTextPosition(JLabel.CENTER);
        
        labelDetener.setText("Salir del Juego");
        labelDetener.setHorizontalTextPosition(JLabel.CENTER);
        labelDetener.setVerticalTextPosition(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelReanudar = new javax.swing.JLabel();
        labelDetener = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 99, 97));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 60)); // NOI18N
        jLabel1.setText("Juego en Pausa");

        labelReanudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_aceptar.png"))); // NOI18N

        labelDetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagaiden/Caja_cancelar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(labelReanudar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(labelDetener)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReanudar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDetener, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(236, 236, 236))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDetener;
    private javax.swing.JLabel labelReanudar;
    // End of variables declaration//GEN-END:variables
}
