/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

import javax.swing.ImageIcon;

/**
 *
 * @author axelsuarez
 */
public class PizzaInvaders extends javax.swing.JPanel {
    
    /**
     * Creates new form PizzaInvaders
     */
    public PizzaInvaders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizzaShip = new javax.swing.JLabel();
        pizza1 = new javax.swing.JLabel();
        pizza2 = new javax.swing.JLabel();
        pizza3 = new javax.swing.JLabel();
        pizza4 = new javax.swing.JLabel();
        pizza5 = new javax.swing.JLabel();
        pizza7 = new javax.swing.JLabel();
        pizza9 = new javax.swing.JLabel();
        pizza10 = new javax.swing.JLabel();
        pizza11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 99, 97));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pizzaShip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaShip_PizzaInvaders.png"))); // NOI18N
        add(pizzaShip, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 537, -1, -1));

        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 154, -1, -1));

        pizza2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 154, -1, -1));

        pizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza3, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 154, -1, -1));

        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza4, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 154, -1, -1));

        pizza5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza5, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 154, -1, -1));

        pizza7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza7, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 261, -1, -1));

        pizza9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza9, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 261, -1, -1));

        pizza10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza10, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 261, -1, -1));

        pizza11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Pizzitas_PizzaInvader.png"))); // NOI18N
        add(pizza11, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 261, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/Fuego_PizzaInvaders.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 457, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pizza1;
    private javax.swing.JLabel pizza10;
    private javax.swing.JLabel pizza11;
    private javax.swing.JLabel pizza2;
    private javax.swing.JLabel pizza3;
    private javax.swing.JLabel pizza4;
    private javax.swing.JLabel pizza5;
    private javax.swing.JLabel pizza7;
    private javax.swing.JLabel pizza9;
    private javax.swing.JLabel pizzaShip;
    // End of variables declaration//GEN-END:variables
}
