/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagaiden;

/**
 *
 * @author axelsuarez
 */
public class Pizzarama extends javax.swing.JPanel {

    /**
     * Creates new form Pizzarama
     */
    public Pizzarama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizzaMem = new javax.swing.JLabel();
        pizzaMem1 = new javax.swing.JLabel();
        pizzaMem2 = new javax.swing.JLabel();
        pizzaMem3 = new javax.swing.JLabel();
        pizzaMem4 = new javax.swing.JLabel();
        pizzaMem5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 99, 97));

        pizzaMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaMemorama.png"))); // NOI18N

        pizzaMem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaMemorama.png"))); // NOI18N

        pizzaMem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaMemorama.png"))); // NOI18N

        pizzaMem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaMemorama.png"))); // NOI18N

        pizzaMem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaMemorama.png"))); // NOI18N

        pizzaMem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsc/PizzaMemorama.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(pizzaMem3)
                        .addGap(93, 93, 93)
                        .addComponent(pizzaMem)
                        .addGap(119, 119, 119)
                        .addComponent(pizzaMem1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(pizzaMem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pizzaMem4)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(437, Short.MAX_VALUE)
                    .addComponent(pizzaMem5)
                    .addGap(413, 413, 413)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pizzaMem1)
                    .addComponent(pizzaMem)
                    .addComponent(pizzaMem3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizzaMem2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pizzaMem4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(90, 90, 90))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(470, Short.MAX_VALUE)
                    .addComponent(pizzaMem5)
                    .addGap(80, 80, 80)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pizzaMem;
    private javax.swing.JLabel pizzaMem1;
    private javax.swing.JLabel pizzaMem2;
    private javax.swing.JLabel pizzaMem3;
    private javax.swing.JLabel pizzaMem4;
    private javax.swing.JLabel pizzaMem5;
    // End of variables declaration//GEN-END:variables
}
